void (() => {
  try {
    console.log()
  } catch (error) {
    console.error(error)
  }
})()
